FROM node:10.12.0-alpine

LABEL maintainer="NHS Digital Delivery Centre,  Team-Grads"

ARG REQUEST_HOST
ARG WORK_DIR=/visitorpwa

RUN apk -q update && apk -q upgrade \
 && apk -q add curl \
 && apk -q add bash \
 && apk -q add bash-completion \
 #install node packages
 && npm install -g http-server \
 #purge cache
 && rm -rf /var/cache/apk/* \
 # run install node build dependencies
 && mkdir $WORK_DIR


WORKDIR $WORK_DIR

COPY package.json $WORK_DIR/package.json

RUN npm install

COPY . $WORK_DIR/.

RUN npm run build

HEALTHCHECK --interval=1m30s --timeout=10s --retries=10 \
     CMD /bin/bash healthcheck.sh


EXPOSE $PORT

CMD ["/bin/bash", "start.sh"]
