version: '3'
services:
    database-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./database_api/Dockerfile
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - DB_FILE
        ports:
            - 5000:5000
        volumes:
            - ./production/database:/home/database
            - ./production/log:/home/log
    database-admin:
        restart: unless-stopped
        build:
            context: ./database_admin/
        environment:
            - HOST=0.0.0.0
            - PORT=5001
            - DB_FILE
        ports:
            - 5001:5001
        volumes:
            - ./production/database:/home/database
    print:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./printing/Dockerfile
        environment:
            - HOST=0.0.0.0
            - PORT=5002
        ports:
            - 5002:5002
        volumes:
            - ./production/log:/home/log
    frontend:
        restart: unless-stopped
        build:
            context: './frontend'
        environment:
            - HOST=0.0.0.0
            - PORT=5003
            - REQUEST_HOST
        ports:
            - 5003:5003
