version: '3'
services:
    backup:
        restart: unless-stopped
        build:
            context: './backup/'
        environment:
            - HOST=0.0.0.0
            - PORT=5004
            - DB_FILE
            - DROPBOX_TOKEN
        ports:
            - 5004:5004
        volumes:
            - /opt/visitorsignin/database:/backupservice/database
            - /opt/visitorsignin/log:/backupservice/log
            - ${OFFLINE_BACKUP_PATH}:/backupservice/offline_backup
    database-api:
        restart: unless-stopped
        build:
            context: ./database_api/
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - DB_FILE
        ports:
            - 5000:5000
        volumes:
            - /opt/visitorsignin/database:/databaseapi/database
            - /opt/visitorsignin/log:/databaseapi/log
        depends_on:
            - backup
    database-admin:
        restart: unless-stopped
        build:
            context: ./database_admin/
        environment:
            - HOST=0.0.0.0
            - PORT=5001
            - DB_FILE
        ports:
            - 5001:5001
        volumes:
            - /opt/visitorsignin/database:/databaseadmin/database
        depends_on:
            - backup
    print:
        restart: unless-stopped
        build:
            context: './printing'
        environment:
            - HOST=0.0.0.0
            - PORT=5002
        ports:
            - 5002:5002
        volumes:
            - /opt/visitorsignin/log:/printservice/log
            - /opt/visitorsignin/template:/printservice/template
    frontend:
        restart: unless-stopped
        build:
            context: './frontend'
        environment:
            - HOST=0.0.0.0
            - PORT=5003
            - REQUEST_HOST
        ports:
            - 5003:5003
