version: '3'
services:
    visitor-flask:
        build: ./flask_app/
        ports:
            - 5000:5000
        volumes:
            - /opt/visitor-db/database:/visitor-app/database
            - /opt/visitor-db/log/flask:/visitor-app/log
    visitor-database:
        build:
            context: ./database/
            args:
                API_TOKEN: "apitoken test"
        ports:
            - 5001:5001
        volumes:
            - /opt/visitor-db/database:/visitor-db/database
            - /opt/visitor-db/log/backup:/visitor-db/log
