version: '3'
services:
    visitor-flask:
        build:
            context: ./flask_app/
            args:
                BRANCH: "tw-docker"
        ports:
            - 5000:5000
        volumes:
            - /opt/visitor-db/database:/visitor-app/database
            - /opt/visitor-db/log/flask:/visitor-app/log
    visitor-database:
        build:
            context: ./database/
            args:
                BRANCH: "tw-docker"
        ports:
            - 5001:5001
        volumes:
            - /opt/visitor-db/database:/visitor-db/database
    visitor-backup:
        build:
            context: './backup/'
            args:
                BRANCH: "tw-docker"
                API_TOKEN: "apitoken"
        volumes:
            - /opt/visitor-db/database:/visitor-back/database
            - /opt/visitor-db/log/backup:/visitor-back/log
