version: '3'
services:
    backup:
        restart: always
        build:
            context: './backup/'
            args:
                API_TOKEN: "${DROPBOX_TOKEN}"
                DB_FILE: "${DB_FILE}"
        volumes:
            - /opt/visitorsignin/database:/backupservice/database
            - /opt/visitorsignin/log:/backupservice/log
    database-api:
        restart: always
        build:
            context: ./database_api/
        environment:
            - HOST=0.0.0.0
            - PORT=5000
            - DB_FILE
        ports:
            - 5000:5000
        volumes:
            - /opt/visitorsignin/database:/databaseapi/database
            - /opt/visitorsignin/log:/databaseapi/log
    database-admin:
        restart: always
        build:
            context: ./database_admin/
        environment:
            - HOST=0.0.0.0
            - PORT=5001
            - DB_FILE
        ports:
            - 5001:5001
        volumes:
            - /opt/visitorsignin/database:/databaseadmin/database
    print:
        restart: always
        build:
            context: './printing'
        environment:
            - HOST=0.0.0.0
            - PORT=5002
        ports:
            - 5002:5002
        volumes:
            - /opt/visitorsignin/log:/printservice/log
    frontend:
        restart: always
        build:
            context: './frontend'
        environment:
            - HOST=0.0.0.0
            - PORT=5003
            - REQUEST_HOST
        ports:
            - 5003:5003
