version: '3'
services:
    visitor-backup:
        build:
            context: './backup/'
            args:
                BRANCH: "${BRANCH}"
                API_TOKEN: "${DROPBOX_TOKEN}"
                DB_FILE: "${DB_FILE}"
        volumes:
            - /opt/visitor-db/database:/visitor-back/database
            - /opt/visitor-db/log/backup:/visitor-back/log
    visitor-flask:
        build:
            context: ./flask_app/
            args:
                BRANCH: "${BRANCH}"
                DB_FILE: "${DB_FILE}"
        ports:
            - 5000:5000
        volumes:
            - /opt/visitor-db/database:/visitor-app/database
            - /opt/visitor-db/log/flask:/visitor-app/log
    visitor-database:
        build:
            context: ./database/
            args:
                BRANCH: "${BRANCH}"
                DB_FILE: "${DB_FILE}"
        ports:
            - 5001:5001
        volumes:
            - /opt/visitor-db/database:/visitor-db/database
