FROM python:3.7-alpine
LABEL maintainer="NHS Digital Delivery Centre,  Team-Grads"

ARG DB_FILE

ARG WORK_DIR=/databaseadmin

ENV PORT=5001
ENV HOST=0.0.0.0
ENV DB_PATH $WORK_DIR/database/$DB_FILE

COPY . $WORK_DIR/.

RUN apk -q update && apk -q upgrade \
 && apk -q add curl \
 #install python packages
 && pip install -qr $WORK_DIR/requirements.txt \
 #purge cache
 && rm -rf /var/cache/apk/* \
 #make work directory
 && mkdir $WORK_DIR/log \
 && mkdir $WORK_DIR/database

WORKDIR $WORK_DIR

HEALTHCHECK --interval=1m30s --timeout=10s --retries=10 \
    CMD /bin/sh healthcheck.sh

EXPOSE $PORT
CMD ["/bin/sh", "start.sh"]
