FROM python:3.7-slim

LABEL maintainer="NHS Digital Delivery Centre,  Team-Grads"

ARG WRK_DIR=/printservice
ENV PORT 5002
ENV HOST 0.0.0.0
ENV LOG_PATH $WRK_DIR/log/print.log

COPY requirements.txt /tmp/

RUN apt-get update \
 && apt-get install -y \
 bash \
 curl \
 cups \
 cups-client \
 python3-dev \
 libcups2-dev \
 iproute2 \
 fonts-liberation \
 #install python libraries
 && pip3 install -r /tmp/requirements.txt \
 #remove build dependencies and purge cache
 && apt-get purge -y --auto-remove \
 gcc \
 libcups2-dev \
 python3-dev \
 && rm -rf /var/lib/apt/lists/* \
 #make working directories
 && mkdir $WRK_DIR \
 && mkdir $WRK_DIR/log \
 && touch /etc/cups/client.conf

COPY ./printapi $WRK_DIR/printapi/
COPY ./template $WRK_DIR/template/
COPY ./main.py $WRK_DIR/
COPY ./start.sh $WRK_DIR/

HEALTHCHECK --interval=1m30s --timeout=10s --retries=10 \
    CMD curl --fail http://$HOST:$PORT/status || exit 1

WORKDIR $WRK_DIR
EXPOSE ${PORT}

CMD ["/bin/bash", "start.sh"]
