function getFormInput(id) {
    return cy.get(`${id} .el-form-item__content .el-input input`)
}

function getFormError(id) {
    return cy.get(`${id} .el-form-item__content .el-form-item__error`)
}

describe('Form Tests', () => {
    //Signin tests
    it('Test empty fields sign in', () => {
        cy.visit('/#/signin')
        cy.get('#btnConfirm').click()
        getFormError('#name').contains('Please input your first name')
        getFormError('#surname').contains('Please input your last name')
        getFormError('#visiting').contains('Please input who you are visiting')
        getFormError('#company').should('not.exist')
    })

    it('Test input field length sign in', () => {
        cy.visit('/#/signin')
        getFormInput('#name').type('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#surname').type('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#visiting').type('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#company').type('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#name').should('have.value', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#surname').should('have.value', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#visiting').should('have.value', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#company').should('have.value', 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
    })

    it('Test name input validation', () => {
        cy.visit('/#/signin')
        getFormInput('#name').type('123')
        cy.get('#btnConfirm').click()
        getFormError('#name').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#name').type('test name')
        cy.get('#btnConfirm').click()
        getFormError('#name').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#name').type('test-name')
        cy.get('#btnConfirm').click()
        getFormError('#name').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#name').type('testname')
        cy.get('#btnConfirm').click()
        getFormError('#name').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#name').type('TESTNAME')
        cy.get('#btnConfirm').click()
        getFormError('#name').should('not.exist')
    })

    it('Test surname input validation', () => {
        cy.visit('/#/signin')
        getFormInput('#surname').type('123')
        cy.get('#btnConfirm').click()
        getFormError('#surname').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#surname').type('test surname')
        cy.get('#btnConfirm').click()
        getFormError('#surname').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#surname').type('test-surname')
        cy.get('#btnConfirm').click()
        getFormError('#surname').contains('Accepted characters: A-Z, a-z')
        cy.get('#btnReset').click()
        getFormInput('#surname').type('testsurname')
        cy.get('#btnConfirm').click()
        getFormError('#surname').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#surname').type('TESTSURNAME')
        cy.get('#btnConfirm').click()
        getFormError('#surname').should('not.exist')
    })

    it('Test visiting input validation', () => {
        cy.visit('/#/signin')
        getFormInput('#visiting').type('123')
        cy.get('#btnConfirm').click()
        getFormError('#visiting').contains('Accepted characters: A-Z, a-z and space')
        cy.get('#btnReset').click()
        getFormInput('#visiting').type('test-visiting')
        cy.get('#btnConfirm').click()
        getFormError('#visiting').contains('Accepted characters: A-Z, a-z and space')
        cy.get('#btnReset').click()
        getFormInput('#visiting').type('testvisiting')
        cy.get('#btnConfirm').click()
        getFormError('#visiting').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#visiting').type('test visiting')
        cy.get('#btnConfirm').click()
        getFormError('#visiting').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#visiting').type('TEST VISITING')
        cy.get('#btnConfirm').click()
        getFormError('#visiting').should('not.exist')
    })

    it('Test company input validation', () => {
        cy.visit('/#/signin')
        getFormInput('#company').type('test-company')
        cy.get('#btnConfirm').click()
        getFormError('#company').contains('Accepted characters: A-Z, a-z, 0-9 and space')
        cy.get('#btnReset').click()
        getFormInput('#company').type('testcompany')
        cy.get('#btnConfirm').click()
        getFormError('#company').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#company').type('test company')
        cy.get('#btnConfirm').click()
        getFormError('#company').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#company').type('test company123')
        cy.get('#btnConfirm').click()
        getFormError('#company').should('not.exist')
        cy.get('#btnReset').click()
        getFormInput('#company').type('TEST COMPANY')
        cy.get('#btnConfirm').click()
        getFormError('#company').should('not.exist')
    })

    it('Test confirm dialog', () => {
        cy.visit('/#/signin')
        getFormInput('#name').type('firstname')
        getFormInput('#surname').type('surname')
        getFormInput('#visiting').type('visiting')
        getFormInput('#company').type('company')
        cy.get('#btnConfirm').click()
        cy.get('#confirmName').contains('firstname surname')
        cy.get('#confirmVisiting').contains('visiting')
        cy.get('#confirmCompany').contains('company')
    })

    //SignOut tests
    it('Test empty fields sign out', () => {
        cy.visit('/#/signout')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Please input Pass ID')
    })

    it('Test input field length sign in', () => {
        cy.visit('/#/signout')
        getFormInput('#passId').type('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
        getFormInput('#passId').should('have.value', 'aaaaaa')
    })

    it('Test pass id input validation', () => {
        cy.visit('/#/signout')
        getFormInput('#passId').type('111111')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Pass ID has format: 0000a')
        cy.get('#btnReset').click()
        getFormInput('#passId').type('aaaaaa')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Pass ID has format: 0000a')
        cy.get('#btnReset').click()
        getFormInput('#passId').type('aaa111')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Pass ID has format: 0000a')
        cy.get('#btnReset').click()
        getFormInput('#passId').type('111aaa')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Pass ID has format: 0000a')
        cy.get('#btnReset').click()
        getFormInput('#passId').type('11111A')
        cy.get('#btnConfirm').click()
        getFormError('#passId').contains('Pass ID has format: 0000a')
    })
})
